version: '3.2'
services:  
    db:
      image: "mcr.microsoft.com/mssql/server"   
      environment:
          SA_PASSWORD: "mySecurePassword123*1"
          ACCEPT_EULA: "Y"
      ports:         
        - 5002:1433
    currency-market-webapi:
      ports:
        - 5001:80
      depends_on:
        - db            
      environment:
        ASPNETCORE_ENVIRONMENT: "Docker" 
      build:
        context: ./
        dockerfile: CurrencyMarket.WebApi/Dockerfile